fix dotnet builder types
DevCycleHQ/dotnet-server-sdk pull request #36
Opened 2022-12-13 23:24 UTC by ajwootto

Use generics to return the correct builder type from each implementation of the abstract builder class.

Also return the correct kind of client from the `Build` calls.

This allows you to get the correct types without casting:

```
DVCLocalClient client = new DVCLocalClientBuilder()
                    .SetEnvironmentKey(clientBody.sdkKey)
                    .SetOptions(clientBody.options)
                    .SetInitializedSubscriber((o, e) =>
                    {

                    })
                    .SetLogger(new LoggerFactory())
                    .Build();
```

2022-12-13 23:35 UTC, JamieSinn commented
Does this work when targeting a lower C# version? Not sure if this kind of generics is supported in Core 3.1

2022-12-14 00:19 UTC, ajwootto commented
> Does this work when targeting a lower C# version? Not sure if this kind of generics is supported in Core 3.1

Yeah generics were added in like C# 2.0 and as far as I can tell we only support C# 10 and above (if I change the LangVersion to anything lower than that the build fails)

2022-12-14 16:10 UTC, JamieSinn requested changes

2022-12-14 16:10 UTC, JamieSinn commented on DevCycle.SDK.Server.Cloud/Api/DVCCloudClient.cs
>  namespace DevCycle.SDK.Server.Cloud.Api
Make sure to update tests

2022-12-14 16:43 UTC, JamieSinn approved these changes

2022-12-14 16:44 UTC, merged